language: python
python:
  - "3.6"
  - "3.7-dev"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls==1.7.0
script: nosetests --with-coverage --cover-package=betterreads
after_success: coveralls
