language: python
python:
  - "3.6"
  - "3.7-dev"
before_install:
  - openssl aes-256-cbc -K $encrypted_2f1e0e39ed26_key -iv $encrypted_2f1e0e39ed26_iv
    -in apikey.py.enc -out goodreads/apikey.py -d
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script: nosetests --with-coverage --cover-package=goodreads
after_success: coveralls
